version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker: 
      - image: mcr.microsoft.com/mssql/server:2019-latest
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: /bin/bash -c 'python -m pytest -v test/integration/sqlserver.dbtspec'
          # /bin/bash -c 'python -m pytest --durations 0 -v -m profile_snowflake {posargs} -n4 test/integration/sqlserver.dbtspec'
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
