version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  build-and-test:
    docker: 
      - image: dataders/pyodbc:1.2
    executor: python/default 
    steps:
      - checkout
      - run:
          # ONLY UNTIL NEW RC OF UPSTREAM
          name: TEMP install git
          command: |
            apt-get update
            apt-get install -y git
      - python/install-packages:
          pkg-manager: pip
          pypi-cache: false
      - run:
          name: Test
          command: tox -e integration-synapse

workflows:
  main:
    jobs:
      - build-and-test:
          context:
            - DBT_SYNAPSE_PROFILE
