version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  integration-sqlserver: &sqlserver
    docker: 
      - image: dataders/pyodbc:1.4
      - image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
          ACCEPT_EULA: 'yes'
          MSSQL_SA_PASSWORD: 5atyaNadella
          MSSQL_IP_ADDRESS: 0.0.0.0
    executor: python/default 
    steps:
      - checkout
      - run:
          name: wait for SQL Server container to set up
          command: sleep 30
      - run:
          name: test connection via SQL CMD
          command: sqlcmd -S 'localhost,1433' -U sa -P 5atyaNadella -Q 'create database blog'
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Test adapter on SQL Server against dbt-adapter-tests
          command: tox -e integration-sqlserver
  connection-sqlserver:
    <<: *sqlserver
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: wait for SQL Server container to set up
          command: sleep 30
      - run:
          name: prep for connecting
          command: |
            mkdir -p ~/.dbt
            cd test/integration
            cp sample.profiles.yml ~/.dbt/profiles.yml
            
      - run:
          name: cnxn -- SQL Server - local sql cred
          command: |
            cd test/integration
            dbt compile --target sqlserver_local_userpass
      - run:
          name: cnxn -- Azure SQL - sql cred
          command: |
            cd test/integration
            dbt compile --target azuresql_sqlcred
      - run:
          name: cnxn -- Azure SQL - SQL cred
          command: |
            cd test/integration
            dbt compile --target azuresql_sqlcred
      - run:
          name: cnxn -- Azure SQL - AAD Password
          command: |
            cd test/integration
            dbt compile --target azuresql_aad
  integration-azuresql:
    docker: 
      - image: dataders/pyodbc:1.4
    executor: python/default 
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Test adapter on Azure SQL against dbt-adapter-tests
          command: tox -e integration-azuresql

workflows:
  main:
    jobs:
      - integration-sqlserver
      - integration-azuresql:
          context:
            - DBT_SYNAPSE_PROFILE
      - connection-sqlserver:
          context:
            - DBT_SYNAPSE_PROFILE
