version: 2.1

orbs:
  python: circleci/python@1.1.0

jobs:
  build-and-test:
    docker: 
      - image: laudio/pyodbc
      # - image: dataders/pyodbc:1.0
      # - image: dataders/dbtsynapse:1.0
      # - image: mcr.microsoft.com/mssql/server:2019-latest # doesn't have git?!
    executor: python/default 
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Test
          command: tox -e integration-synapse

workflows:
  main:
    jobs:
      - build-and-test:
          context:
            - DBT_SYNAPSE_PROFILE
